### ISSUE TITLE
[Client] Home 목업페이지 구현

### ISSUE THREAD

**Issue by GWANGUIAN** [codestates/slow-postbox#11]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: Home 목업페이지 구현

### TODO
1. [ ] 숫자 카운팅 업 애니메이션 구현
2. [ ] 스크롤 페이드 인 애니메이션 구현
3. [ ] 웹페이지 설명 스크립트 작성

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Middle`
