### ISSUE TITLE
[Client] 관리자페이지 목업 구현

### ISSUE THREAD

**Issue by GWANGUIAN** [codestates/slow-postbox#12]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 관리자페이지 목업 구현

### TODO
1. [ ] 유저정보/편지관리 탭 구현
2. [ ] 유저 정보 페이지 구현
3. [ ] 편지 관리 페이지 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Middle`
