### ISSUE TITLE
[Client] 메일작성 페이지 css 수정

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#158]
### ISSUE
- Group:  `client`
- Type: `design`
- Detail: Editor.css, PreviewModal.css 수정

### TODO
1. [ ] 에디터 높이 css vh로 단위 수정
2. [ ] previewModal.css table 부분 border 속성 수정
3. [ ] formInfo.content 부분  div에 overflow: scroll 속성 추가

### Labels
- Estimated time: `E: 0.5h`
- Group : `client`
- Sprint: `Sprint 3`
- Urgency: `High`
