### ISSUE TITLE
[Client]받은편지함 컴포넌트 목업 구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#17]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 받은편지함/도착예정 편지함 목업 구현

### TODO
1. [ ] 받은편지 개수에 따른 목업 구현
2. [ ] 도착예정 편지 개수에 따른 목업 구현
3. [ ] 페이지네이션 목업 구현
4. [ ] 받은편지함/보낸편지함 Notification 알림모양 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `Middle`
