### ISSUE TITLE
[Client] 마이페이지, 메일쓰기 페이지 css 수정 및 이메일 템플릿 수정

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#175]
### ISSUE
- Group:  `client`
- Type: `design`
- Detail: 페이지 css 세부 수정 및 회원가가입 시 발송되는 인증메일 템플릿 수정

### TODO
1. [ ] 마이페이지 활동로그 클래스 overflow: scroll 적용하기
2. [ ] 마이페이지 .mypage-container 높이 수정 
3. [ ] 마이페이지 PreviewModal.css border 지우기
4. [ ] 회원가입 인증메일 템플릿 수정

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 3`
- Urgency: `High`
