### ISSUE TITLE
[Client] 회원가입 페이지 목업구현

### ISSUE THREAD

**Issue by lim-yubin** [codestates/slow-postbox#18]
### ISSUE
- Group:  `client`, 
- Type: `mockup`
- Detail: `회원가입페이지 목업구현`

### TODO
1. [ ] 이메일, 이름 입력란 구현
2. [ ] 비밀번호, 비밀번호 확인 입력란 구현
3. [ ] 이메일 인증코드 발송버튼 구현
4. [ ]  이메일 인증코드 발송버튼 클릭시 인증코드 입력란 활성화 구현 

### Labels
- Estimated time: `E:2h`
- Group : `client`,
- Sprint: `1`
- Urgency: `Middle`
