### ISSUE TITLE
[Refactor] 메일작성 페이지 

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#189]
### ISSUE
- Group:  `refactor`
- Type: `feature`

### TODO
1. [ ] 모달 미리보기 오버플로우 속성변경
2. [ ] 메일 전송시 보낸 편지함으로 이동
3. [ ] datepicker z-index 수정
4. [ ] 메일 전송시 모달창 z-index 수정
5. [ ] 이미지 파일 크기 제한
6. [ ] 반응형

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
