### ISSUE TITLE
[Client] 마이페이지 목업구현

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#19]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 비밀번호 인풋 필드에 값 유효성 검사 결과에 따른 메시지 띄우기

### TODO
1. [ ] 비밀번호 유효성 검사 함수 생성
2. [ ] 새로운 비밀번호, 확인 비밀번호 상태 생성
3. [ ] 인풋 필드 입력에 따른 상태 변경
4. [ ] 상태 유효성검사 결과에 따른 메시지 띄우기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Middle`
