### ISSUE TITLE
[Server] 게스트 로그인 관련 서버 기능 추가

### ISSUE THREAD

**Issue by GWANGUIAN** [codestates/slow-postbox#202]
### ISSUE
- Group:  `server`
- Type:  `feature`

### TODO
1. [ ] users 테이블 isGuest 컬럼 추가
2. [ ] 게스트 로그인 요청 추가(유저 데이터 생성 및 accessToken 발급)
3. [ ] 로그아웃 시 게스트 유저 정보 삭제

### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint 4`
