### ISSUE TITLE
[Client] 보낸편지함 컴포넌트 목업 구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#21]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 보낸편지함/전달예정 편지함 목업 구현

### TODO
1. [ ] 보낸편지 개수에 따른 목업 구현
2. [ ] 전달예정 편지 개수에 따른 목업 구현
3. [ ] 페이지네이션 목업 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `Middle`
