### ISSUE TITLE
[Refactor] 메일작성페이지, 마이페이지 api 수정

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#218]
### ISSUE
- Group:  `client`, `server`
- Type: `refactor`
- Detail: 변경된 깃북 api에 따른 경로 및 파일명 등 수정하기

### TODO
1. [ ] 메일작성 페이지 네트워크 요청 경로 수정
2. [ ] 마이페이지 네트워크 요청 경로 수정
3. [ ] 파일명 수정 및 router 수정

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__4`
- Urgency: `Low`
