### ISSUE TITLE
[Client] 마이페이지 내 Withdrawal 컴포넌트 목업 구현

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#24]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 마이페이지 정보수정 탭에서 탈퇴하기 버튼 클릭시 Withdrawal 컴포넌트 보이기

### TODO
1. [ ] Withdrawal 컴포넌트 목업 생성
2. [ ] 비밀번호 상태 생성
3. [ ] 마이페이지에서 탈퇴하기 버튼에 따른 isWithdrawalOpen 상태 생성
4. [ ] isWithdrawalOpen에 따른 컴포넌트 보이기 구현

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Middle`
