### ISSUE TITLE
[Refactor] 받은편지함/보낸편지함 코드 변경

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#242]
### ISSUE
- Group:  `client`
- Type: `Refactor`
- Detail : 받은편지함, 보낸편지함 삼항연산자 코드 수정

### TODO
1. [ ] ReceiveMail.js / SentMail.js 삼항연산자 수정
2. [ ] MailView CSS수정 ( 삭제모달 , 버튼위치 )
3. [ ] Mail 삭제 api 주소 수정
