### ISSUE TITLE
[Client] 메일작성 페이지 css 수정

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#29]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 메일작성 페이지 내 Mailform 컴포넌트 css 수정
### TODO
1. [ ] max-width, min-width, width, height 수정
2. [ ] font 관련 size, font-weight, :hover 수정
3. [ ] 전체적인 색깔, border, box-shadow 등 수정

### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Middle`
