### ISSUE TITLE
[Client] 받은편지함/도착편지함 CSS 수정

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#30]
### ISSUE
- Group:  `client`
- Type: `css`
- Detail: 받은편지함/도착편지함 CSS 수정

### TODO
1. [ ] 받은편지함 / 도착예정편지함 CSS 수정
2. [ ] 보낸편지함 / 전달예정 편지함 CSS 수정
3. [ ] 각 편지함 페이지네이션 CSS 수정
4. [ ] 받은편지함 Nofitication CSS 수정

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `Middle`
