### ISSUE TITLE
[Client] 메일작성 페이지 내 미리보기 목업 구현(1)PreviewModal

### ISSUE THREAD

**Issue by sohhyeonkim** [codestates/slow-postbox#31]
### ISSUE
- Group:  `client`
- Type: `mock-up`
- Detail: 미리보기 구현 시 나타나는 PreviewModal 안에 받은편지함 컴포넌트 삽입하기
 
### TODO
1. [ ] 받은편지함 컴포넌트 import 해오기
2. [ ] 상위 Mailform 컴포넌트에 상태 생성해서 props로 하위 컴포넌트로 상태, 상태변경함수 내려주기
3. [ ] 상태를 받은편지함 컴포넌트에 적용하기

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `Low`
