### ISSUE TITLE
[Server] 회원가입 기능구현(1)

### ISSUE THREAD

**Issue by lim-yubin** [codestates/slow-postbox#36]
### ISSUE
- Group:  `server`
- Type:  `feature`
- Detail: `회원가입/이메일인증코드 기능구현`

### TODO
1. [ ] 인증코드발송버튼 클릭시 입력한 이메일로 코드 전송
2. [ ] 인증코드발송버튼 클릭시 인증코드 입력란 활성화
3. [ ] 인증코드 일치 여부 유효성 검사

### Labels
- Estimated time: `E: 2.5h`
- Group :  `server`
- Sprint:  `2`
- Urgency:  `Middle`
