### ISSUE TITLE
[Server] 유저 정보 페이지 기능 구현

### ISSUE THREAD

**Issue by GWANGUIAN** [codestates/slow-postbox#40]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`
- Detail: 관리자페이지>유저 정보 페이지 기능 구현

### TODO
1. [ ] 유저 정보 응답/요청 구현
2. [ ] 회원 탈퇴 응답/요청 구현
3. [ ] 페이지네이션 및 검색 기능 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint 2`
- Urgency: `Middle`
