### ISSUE TITLE
[Server] 편지 관리 페이지 기능 구현

### ISSUE THREAD

**Issue by GWANGUIAN** [codestates/slow-postbox#41]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`
- Detail: 관리자페이지>편지 관리 페이지 기능 구현

### TODO
1. [ ] 편지 리스트 요청/응답 구현
2. [ ] 편지 삭제 요청/응답 구현
3. [ ] 페이지네이션 및 검색 기능 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint 2`
- Urgency: `Middle`
