### ISSUE TITLE
[Server] 받은편지함/도착예정편지함 컴포넌트 기능구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#42]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 받은편지함 컴포넌트 기능 구현

### TODO
1. [ ] 로그인 시 받아온 data로 받은편지함 화면 랜더링
2. [ ] 각 편지의 data에(받은메일/도착예정) 따른 편지 list 랜더링 기능 구현
3. [ ] 편지 개수에 따른 화면 랜더링 기능 구현
4. [ ] 편지 읽을 시 편지모양/읽음 Check 변경 기능 구현
5. [ ] 페이지네이션 기능 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint1`
- Urgency: `High`
