### ISSUE TITLE
[Server] 로그인(일반)기능구현

### ISSUE THREAD

**Issue by lim-yubin** [codestates/slow-postbox#43]
### ISSUE
- Group:  `server`
- Type:  `feature`
- Detail: `이메일, 비밀번호 입력시 로그인 기능 구현`

### TODO
1. [x] 이메일 및 비밀번호 db에 존재 유무 확인 후 일치하면 로그인성공
2. [x] 로그인 성공시 토큰 전달(isLogin 과 같은 여부 확인으로 회원의 로그인상태 여부 상시 확인 가능해야함)
2. [x] 로그인 성공시 '메인페이지(/home)'으로 이동
3. [ ] 로그아웃 기능구현

### Labels
- Estimated time: `E: 2.5h`
- Group :  `server`
- Sprint: `2.5`
- Urgency: `Middle`
