### ISSUE TITLE
[Server] 보낸편지함/전달예정편지함 컴포넌트 기능구현 

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#44]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 보낸편지함 컴포넌트 기능 구현

### TODO
1. [ ] 로그인 시 받아온 data로 받은편지함 화면 랜더링
2. [ ] 각 편지의 data에(보내기완료/전달예정) 따른 편지 list 랜더링 기능 구현
3. [ ] 편지 개수에 따른 화면 랜더링 기능 구현
4. [ ] 보낸 편지 중 상대방이 읽음 유무에 따른 화면 랜더링 기능 구현 
5. [ ] 페이지네이션 기능 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `High`
