### ISSUE TITLE
[server] 받은편지함 편지 View 컴포넌트 기능 구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#60]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 편지 View 컴포넌트 기능 구현

### TODO
1. [ ] 편지함에서 편지 클릭 시 1개의 데이터로 편지 View 랜더링
2. [ ] 편지 메뉴 버튼 클릭 시 삭제/답장 모달 띄우기
3. [ ] 모달 삭제 버튼 클릭 시 data 값 변경 후 삭제
4. [ ] 모달 답장 버튼 클릭 시  받는 사람 고정 후 메일 작성 화면으로 이동
5. [ ] 닫기 버튼 클릭 시 이전화면으로 돌아가기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group :  `server`
- Sprint: `Sprint2`
- Urgency: `High`
