### ISSUE TITLE
[server] 보낸편지함 편지 View 컴포넌트 기능 구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#65]
### ISSUE
- Group:  `server`
- Type:  `feature`
- Detail: 편지 View 컴포넌트 기능 구현

### TODO
1. [ ] 편지함에서 편지 클릭 시 1개의 데이터로 편지 View 랜더링
2. [ ] 편지 메뉴 버튼 클릭 시 삭제 모달 띄우기
3. [ ] 모달 삭제 버튼 클릭 시 data 값 변경 후 삭제
4. [ ] 닫기 버튼 클릭 시 이전화면으로 돌아가기

### Estimated time
> Pick one 
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint2`
- Urgency:  `Middle`
