### ISSUE TITLE
[server] 각 편지함 컴포넌트 검색 필터링 기능 구현

### ISSUE THREAD

**Issue by moonseonyeong** [codestates/slow-postbox#70]
### ISSUE
- Group:  `client`, 
- Type: `feature`
- Detail: 받는편지함/ 도착예정 편지함 / 보낸편지함/ 전달예정 편지함  검색 필터링 기능 구현

### TODO
1. [ ] 각 편지함 화면마다 검색 필터링 (제목) 기능 구현
2. [ ] 보낸편지함 (받는사람 검색 필터링 구현)
3. [ ] 받는편지함 (보낸사람 검색 필터링 구현)

### Labels
- Estimated time: `E:2h`
- Group : `server` 
- Sprint: `Sprint3`
- Urgency:  `Middle`
